kind: pipeline
type: docker
name: java11

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn clean test

---
kind: pipeline
type: docker
name: java13

steps:
  - name: test
    image: maven:3-jdk-14
    commands:
      - mvn clean test
