kind: pipeline
type: docker
name: java11

steps:
  - name: test
    image: maven:3-openjdk-11
    commands:
      - mvn clean test

---
kind: pipeline
type: docker
name: java17

steps:
  - name: test
    image: maven:3-openjdk-17
    commands:
      - mvn clean test
