kind: pipeline
name: java8

clone:
  disable: true

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 10
    skip_verify: true
- name: test
  image: maven:3.5-jdk-8-alpine
  commands:
  - mvn clean test

---
kind: pipeline
name: java11

clone:
  disable: true

steps:
- name: clone
  image: plugins/git
  settings:
    depth: 10
    skip_verify: true
- name: test
  image: maven:3.5-jdk-11-slim
  commands:
  - mvn clean test

