kind: pipeline
type: docker
name: java11

steps:
  - name: test
    image: maven:3-openjdk-11
    commands:
      - mvn clean test

---
kind: pipeline
type: docker
name: java15

steps:
  - name: test
    image: maven:3-openjdk-15
    commands:
      - mvn clean test
